name: flutter_wizard
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4

flutter:
  uses-material-design: true
